### ISSUE TITLE
No longer works on GTK3.18

### ISSUE THREAD

**Issue by Justinzobel** [gnome-mpv/gnome-mpv#155]
Overview Description: You cannot kill gnome-mpv for every distribution that isn't on GTK 3.20.

Steps to Reproduce:
1. Attempt to compile on a distro with < GTK 3.20
2.
3.

Actual Results:
Requested 'gtk+-3.0 >= 3.20' but version of GTK+ is 3.18.7

Expected Results:
Support for GTK 3.18 and older versions.

Version: 0.8

Additional Information:

**Comment by TingPing** [comment]
Obviously that was on purpose, users on distributions with older releases of Gtk are clearly fine with using outdated software.

**Comment by Justinzobel** [comment]
So basically anything that isn't a rolling release isn't supported? That's awesome!

**Comment by TingPing** [comment]
Your distribution is already entirely made up of frozen releases of software, how is that any different in this situation? gnome-mpv 0.7 will continue to work as well as other software you have installed. That is just my opinion though.

**Comment by Justinzobel** [comment]
Solus freezes the core, gtk, glibc etc, but keeps apps up to date. Most
other apps we'll be able to do this but 0.8 of Gnome MPV will not be able
to :(

**Comment by JoshStrobl** [comment]
> Obviously that was on purpose, users on distributions with older releases of Gtk are clearly fine with using outdated software.

Did you honestly say that? Have you never seen PPAs on Ubuntu to get newer software than available in the repository? Stuff in copr or software.opensuse.org? People are clearly **not fine** with it.

While I appreciate all the work that you've done on making gnome-mpv what it is today, I think dropping support for GTK 3.18.x was premature and it would be appreciated if you brought back support for it.

> Your distribution is already entirely made up of frozen releases of software, how is that any different in this situation?

As @Justinzobel elaborted, the [Solus](https://solus-project.com) operating system freezes our GNOME Stack, in addition to GTK, for each major release, where 1.0 has 3.18, 2.0 will have 3.22, so-forth, with a release cadence for major releases being once a year. This isn't some Ubuntu LTS we're talking about.

**Comment by TingPing** [comment]
> While I appreciate all the work that you've done on making gnome-mpv what it is today, I think dropping support for GTK 3.18.x was premature and it would be appreciated if you brought back support for it.

FYI while I have contributed to the project I am not the main developer who made the decision. I was just putting my thoughts out there that *I* think a cleaner codebase outweighs users on older distros.

> The Solus operating system freezes our GNOME Stack, in addition to GTK, for each major release, where 1.0 has 3.18, 2.0 will have 3.22, so-forth, with a release cadence for major releases being once a year. 

Right so you are already missing the entire Gnome stack, is it surprising a Gnome focused application is included in that list?

**Comment by ikeydoherty** [comment]
@TingPing the surprise here is actually that a GNOME focused application doesn't follow GNOME branching, whereby each major supported version receives point releases. As an example, we have
GTK 3.18.7. We're not "missing the entire Gnome stack", I think you're avoiding some key engineering principles here too readily.

Your logic on outdated software is actually flawed, because we use an up to date version (and well maintained) of the stable GNOME branch 3.18 - yet bumping the minimum requirement to 3.20 means that you *made* things out of date. :)

Regardless, flawed logic aside, this is your project. If at some point you become curious as to how you can maintain a project with support for multiple GTK versions, I suggest looking at Budgie Desktop, which capably supports 3.16-3.20 (Though developed on 3.18)

If I find it possible to patch GNOME MPV to work on 3.18 (which I strongly suspect it's not a difficult thing to do at all) - then I shall keep GNOME MPV in our repositories. If not, I shall remove it due to the nature of maintenance suggested so far in this thread.

**Comment by TingPing** [comment]
For the third time I am not the main developer of the project, I probably shouldn't have commented at all.

**Comment by ikeydoherty** [comment]
@TingPing s'all good :) So I had a poke through, the main symbol that GNOME MPV uses from 3.20 is `gtk_widget_queue_allocate` - I'm pretty sure we can cook up a patch in Solus.

**Comment by TingPing** [comment]
@ikeydoherty If you check the commits there was apparently a "sizing bug" that was worked around previously plus various wayland bugs that were fixed in 3.20. Again I didn't make this decision I was just commenting that it was a willing change to bump the version obviously. I didn't expect all of Solus to take that as an official statement...

**Comment by ikeydoherty** [comment]
@TingPing nor did I, the first I knew of this was this morning. That's why I joined in to sort the issue out. As far as I'm concerned, we only need to add simple patches into our version. I've offered my 2 cents into how parallel versions could be handled, but I know myself that `#ifdef`ing your codebase up is messy.

**Comment by gnome-mpv** [comment]
If you revert 80d66ec28bd20c4bd4935cc56a4aa9d80708cce4 and apply the patch below, you should be able to get to work with gtk >= 3.16. However, with gtk 3.20, the window will not resize properly when you toggle the playlist.

````
From 2c6d5a6cdcb9ecc9c634bb2c4663bf4b25b14f3f Mon Sep 17 00:00:00 2001
From: gnome-mpv <gnome-mpv@nowhere>
Date: Tue, 19 Apr 2016 17:36:58 +0700
Subject: [PATCH] Restore compatibility with GTK+ 3.16

---
 configure.ac      | 2 +-
 src/main_window.c | 9 ++++++---
 2 files changed, 7 insertions(+), 4 deletions(-)

diff --git a/configure.ac b/configure.ac
index 615c035..b08b893 100644
--- a/configure.ac
+++ b/configure.ac
@@ -83,7 +83,7 @@ AS_IF([test "x$GLIB_GENMARSHAL" = "x"], [
 	AC_MSG_ERROR([Could not find glib-genmarshal])
 ])
 
-PKG_CHECK_MODULES(DEPS, [gtk+-3.0 >= 3.20 glib-2.0 >= 2.40 mpv >= 1.20 epoxy])
+PKG_CHECK_MODULES(DEPS, [gtk+-3.0 >= 3.16 glib-2.0 >= 2.40 mpv >= 1.20 epoxy])
 
 AC_DEFINE([GLIB_VERSION_MIN_REQUIRED], [GLIB_VERSION_2_40], [Dont warn using older APIs])
 AC_DEFINE([GLIB_VERSION_MAX_ALLOWED], [GLIB_VERSION_2_40], [Prevents using newer APIs])
diff --git a/src/main_window.c b/src/main_window.c
index c947873..2836f04 100644
--- a/src/main_window.c
+++ b/src/main_window.c
@@ -628,7 +628,7 @@ void main_window_resize_video_area(	MainWindow *wnd,
 	 * size_allocate_handler() will be called so that the event handler will
 	 * be disconnected.
 	 */
-	gtk_widget_queue_allocate(wnd->vid_area);
+	gtk_widget_queue_resize(wnd->vid_area);
 }
 
 gboolean main_window_get_use_opengl(MainWindow *wnd)
@@ -747,10 +747,13 @@ void main_window_set_playlist_visible(MainWindow *wnd, gboolean visible)
 
 		if(!maximized)
 		{
+			const gint wnd_offset = main_window_get_csd_enabled(wnd)?
+						52:0;
+
 			gtk_window_resize(	GTK_WINDOW(wnd),
 						visible?
-						width+wnd->playlist_width:
-						handle_pos,
+						width+wnd->playlist_width-wnd_offset:
+						handle_pos+wnd_offset,
 						height );
 		}
 
-- 
2.7.0
````

**Comment by gnome-mpv** [comment]
At this point it seems easy enough to maintain compatibility with gtk >= 3.16. I decided to bump gtk version to 3.20 because the old video autofitting algorithm required rather extensive changes to work properly with it, and I don't want to sprinkle `#ifdef`s everywhere. The new algorithm only requires `gtk_widget_queue_allocate` to be replaced with `gtk_widget_queue_resize`, though this is probably less efficient as it unnecessarily trigger resizes.

There is also a [bug](https://bugzilla.gnome.org/show_bug.cgi?id=755051) in gtk <= 3.20 that pretty much makes autofitting unusable in Wayland. I don't know how to work around this bug.

I'll look into bringing back support for older gtk versions before releasing v0.9. I'll bring back the support if it doesn't require too much work or too messy.

**Comment by xuzhen** [comment]
@ikeydoherty @gnome-mpv  Not only gtk_widget_queue_allocate, the GtkShortcutsWindow widget was also introduced in GTK 3.20

**Comment by ikeydoherty** [comment]
@xuzhen ah see that's what I get for not digging far enough :)

**Comment by ikeydoherty** [comment]
OK guys so should we close this bug, given the `#ifdef` situation we're looking at? We can maintain a small set of patches in Solus for `3.18` support.

Voting time :D

**Comment by gnome-mpv** [comment]
Closing per consensus.

**Comment by gnome-mpv** [comment]
ceeeef1f1de9fe9ca8a669d88d50136d13ceb52b

**Comment by region51** [comment]
@gnome-mpv needed release gnome-mpv-0.9

**Comment by gnome-mpv** [comment]
@region51 I'll make a new release in about a week if there are no new bugs.

**Comment by region51** [comment]
@gnome-mpv ok

**Comment by region51** [comment]
@gnome-mpv gtk-3.16?

**Comment by gnome-mpv** [comment]
@region51: I initially thought I would be able to drop minimum gtk version as far back as 3.16, but  GtkOverlay requires 3.18 so that's as far as I can go.

**Comment by region51** [comment]
@gnome-mpv ok, min gtk3=3.18

**Comment by XRevan86** [comment]
```GTK_CHECK_VERSION(3, 20, 0)``` is better than ```(GTK_MAJOR_VERSION >= 3 && GTK_MINOR_VERSION >= 20)```, as latter will not accept bigger major versions with smaller minor versions.

**Comment by gnome-mpv** [comment]
@XRevan86: Thanks!
3453332a43f64c51e5f15039b8cf876f885eca46
