### ISSUE TITLE
No Next/Previous buttons available

### ISSUE THREAD

**Issue by elkrejzi** [gnome-mpv/gnome-mpv#177]
When using a playlist, I expect to be able to change songs. Currently, that's not possible so easy, as the default available buttons are forward/rewind instead of next/previous. Can the next/previous buttons be implemented somewhere (or let them replace forward/rewind buttons when playlist is on)? Thanks!

**Comment by gnome-mpv** [comment]
gnome-mpv already has next/previous buttons (they only show up when the file has chapters), but, just like the ones in mpv's OSC, they are used to move between chapters rather than playlist entries. I'm not sure if it would be a good idea make them move between playlist entries instead since there is currently no other way to move between chapters using a mouse, but there are already many ways to move between playlist entries: you can double-click on the playlist entry you want to switch to, drag the file from the playlist and drop it onto video area, or press `<` or `>` key.
