### ISSUE TITLE
Cannot adjust volume when the player is fullscreen

### ISSUE THREAD

**Issue by mistguy** [gnome-mpv/gnome-mpv#41]
When the player is in fullscreen mode, clicking the volume button would end up in the disappearance of the bottom toolbar and no volume adjustment widget appears.

Environment:
Archlinux
gnome 3.16
gtk3 3.16.4

**Comment by warmsun0220** [comment]
I also meet this problem ing archlinux.

**Comment by gnome-mpv** [comment]
24c04d7 should stop the toolbar from disappearing. Due to the limitations of GtkPopover, the volume adjustment widget cannot extend beyond the toolbar, so part of it will be cut off. I'm still trying to figure out how to fix it.

Alternatively, you can adjust the volume by putting the cursor over the volume button and scrolling or setting up a keybinding in input.conf.

**Comment by mistguy** [comment]
Gnome mplayer also has this problem, so maybe it is difficult to solve.

**Comment by warmsun0220** [comment]
I am not sure, but how totem solve this problem?
PS: please remove https://github.com/gnome-mpv/gnome-mpv/commit/24c04d757f78608a5b01218a0af9f01fb9e23b1c . I think this problem is not a serious bug, but https://github.com/gnome-mpv/gnome-mpv/commit/24c04d757f78608a5b01218a0af9f01fb9e23b1c  make the interface very very strange.

**Comment by gnome-mpv** [comment]
I think Totem just let gstreamer draw directly onto one of its widget, then use Clutter to draw a toolbar on top. In our case, we embed a foreign mpv window in one of our widget, so we can't just draw things on it.

I have a few ideas for solving this problem. We can try extending the fullscreen toolbar so that it's big enough for the volume control to fit inside, then "cut" the toolbar back down to the correct size by making parts of it invisible. Another way is just to make a new volume control widget that doesn't extend beyond the toolbar. I don't have time to work on this yet though.

@warmsun0220: Is it really better to revert 24c04d7? Having the toolbar disappear after clicking the volume button seems pretty confusing. With 24c04d7, at least the toolbar doesn't disappear and the volume widget is still usable though it is a little awkward.

**Comment by warmsun0220** [comment]
In my opinion, there are a few people to  change the volume through fullscreen toolbar. So I thought  remove volume widget maybe a better idea before solving this problem. 
After reading your comment, maybe your first solution is the best currently.
