### ISSUE TITLE
Add support for the OpenGL renderer

### ISSUE THREAD

**Issue by TingPing** [gnome-mpv/gnome-mpv#57]
Would be a good idea to add support for the mpv OpenGL renderer inside of a GtkGLArea. The main benefit would be solid Wayland support which will be pretty important with Gnome 3.18, a wayland improvement heavy release, coming out soon.

**Comment by gnome-mpv** [comment]
I actually have [a patch](https://gist.github.com/gnome-mpv/6330fffa525d755d4918) for Wayland in my local branch but I haven't been able to test it fully yet. Because of a (recently fixed) [gtk bug](https://bugzilla.gnome.org/show_bug.cgi?id=7541430), you may need to build gtk from git if you want to test it.

**Comment by TingPing** [comment]
> I actually have a patch for Wayland in my local branch but I haven't been able to test it fully yet. 

Seems to work here. Broken link on that bug though.

**Comment by gnome-mpv** [comment]
>Broken link on that bug though.
Here's the correct link: https://bugzilla.gnome.org/show_bug.cgi?id=754143

**Comment by TingPing** [comment]
K, I did experience that crash on 3.17.7. I also experienced a crash when going full-screen.

**Comment by gnome-mpv** [comment]
The crash when going fullscreen was caused by another recently fixed [gtk bug](https://bugzilla.gnome.org/show_bug.cgi?id=754770).
